### ISSUE TITLE
using predict function in td_lstm.py 

### ISSUE THREAD

**Issue by ludens11** [songyouwei/SA-DL#1]
i've tried your code for training purpose and its work really great. now im running this script to predict sentence. its throw me an error.

```
if __name__ == '__main__':
    # model = TDLSTM()
    # model.train()
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--sentence', type=str, default=None, help='predict with sentence')
    args = parser.parse_args()
    model = TDLSTM()
    if args.sentence:
        model.predict(args.sentence) #"Obama is so kind and i love him"
    else:
        model.train()
````

by running `python td_lstm.py -s "Obama is so kind and i love him"` , throw error =

```
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0, ...
```

thanks for your great works for creating this code. really helped me a lot 👍

**Comment by songyouwei** [comment]
@callmefregy I haven't finished the code of the predicting part yet. For TD-LSTM, your need a sentence and a specific aspect.

**Comment by ludens11** [comment]
So , first of all, if i want to predict some sentence, i need to determine manually the aspect ? Or just the whole sentences?
